### ISSUE TITLE
Build assets in shopware bundles

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/shopware-cli#223] opened 2023-08-28 13:52 UTC
### Please describe the feature you would like to see implemented.

As described here https://shyim.me/blog/you-dont-need-a-plugin-to-customize-shopware-6/ you can also have a bundle which contains assets to build.

At the moment, you're only looking for the composer type `shopware-platform-plugin` which is not the case for a bundle (`symfony-bundle`).
https://github.com/FriendsOfShopware/shopware-cli/blob/da3c091602da9ead97fac0c8cd46d6962465b3f5/extension/project.go#L84

Maybe you can introduce some kind of `extra` value that you're looking for which can also indicate for other composer package types that they contain assets?

**Comment by shyim** [comment] 2023-08-28 14:14
We could check if that package contains a `.shopware-extension.yaml` 🤔

**Comment by tinect** [comment] 2023-08-28 14:54
duplicates #201 ?

**Comment by hhoechtl** [comment] 2023-08-28 14:57
Or have an additional list of folders in the `.shopware-extension.yaml`?
I'm not sure which solution would be best suited.

**Comment by shyim** [comment] 2023-09-24 09:11
I close this as it's a duplicate of https://github.com/FriendsOfShopware/shopware-cli/issues/201

**Closed by shyim** 2023-09-24 09:11 UTC
